// DELETE THIS OLD CLASS
@isTest
private class TestUpdateLastActivityDateOnCase
{
    static testMethod void TestUpdateLastActivityDate() 
    {
/*        
        string strSuppliedEmail = 'slammerband@gmail.com';
        string strEmailSubject = 'APEX TEST'; 
        string strCaseOrigin = 'Phone';
        
        RecordType rt = [SELECT Name, Id FROM RecordType WHERE sObjectType = 'Task' AND Name = 'NI Support' AND isActive = true];
        
        Case c = new Case (Description = 'xxx...', Subject = strEmailSubject, Origin = strCaseOrigin, SuppliedEmail = strSuppliedEmail, Status = 'New');
        c.Has_No_DI__c = true;
        insert c;        

        Task tx = new Task(WhatId = c.Id, RecordTypeId = rt.Id);
        insert tx;
*/            
    }
    
}